- src/main/scala/com/codacy/CodacyCoverageReporter.scala
Instead of harcoded string (previously "1.0.0" since forever), now getting the from `build.sbt`
From: http://stackoverflow.com/questions/8957025/sbt-including-the-version-number-in-a-program
Closes #8
> Fix printed version

- README.md
Hi everyone,
when trying to use the codacy-coverage-reporter in Travis CI strictly following the README in this repo, I failed.
However, I figured out a way to use codacy with Travis and I documented it here. If there is a better place for this kind of documentation, please tell me where I should move it. If not, I propose to merge this into master and help others trying to setup codacy with Travis CI.
Regards,
Tobi
> Include documentation for usage with Travis CI

- build.sbt
- project/Dependencies.scala
- src/main/scala/com/codacy/CodacyCoverageReporter.scala
> Note: it will fail the build until codacy-api-scala 2.0.4 and coverage-parser 1.1.14 are released to maven central
> Bump dependencies

- README.md
- src/main/scala/com/codacy/CodacyCoverageReporter.scala
AWS CodeBuild doesn't copy out the .git directory (known issue discussed
here: https://forums.aws.amazon.com/thread.jspa?threadID=244197).
However, they do provide us with an environment variable we
can use.  Put this detection in the CodacyCoverageReporter so that we
can auto-resolve this and not have to use the --commitUUID flag.
[ Documentation: Updated the README ]
[ Testing: Build ]
> CodacyCoverageReporter: Add support for AWS CodeBuild

- README.md
Removed CircleCI since with Workflows (2.0) we cannot seem to get the artifacts from the latest workflow.
> Follow bintray redirects

- README.md
The jar file name pattern described in the README is not consistent with the name of the file.
`codacy-coverage-reporter-4.0.2-assembly.jar` - filename
`codacy-coverage-reporter-<version>-assembly.jar` - format described in README
> Update jar file name pattern

- scripts/publish-native.sh
The existing image tag on the script was removed and the script doesn't run anymore when we're targeting docker.
> Change image to official GraalVM

- src/main/resources/logback.xml
When we changed to StrictLogging instead of LazyLogging [in this commit](https://github.com/codacy/codacy-coverage-reporter/commit/45afbcf0e5ba1e9473e02a64fdb738ee0309f97e) the jar started to assume debug level by default (however, the native image is ok). 
With this the info level is set by default on both artifacts.
> Disables debug level logs by default 

- scripts/publish-native.sh
The native image build got broken after upgrading the graalvm image.
We had to add a new flag to initialize classes and implicitly all of their superclasses during image building (--initialize-at-build-time).
The --no-fallback flag is to avoid falling back to JDK if the build is not successfull and the -report-unsupported-elements-at-runtime flag is to report usage of unsupported methods and fields at run time when they are accessed the first time, instead of as an error during image building.
> fix: Adds new flags to fix the native image build (fixes #125)

- .circleci/config.yml
- .gitignore
- project/Dependencies.scala
- project/build.properties
- src/test/scala/com/codacy/rules/ConfigurationRulesTest.scala
- This bumps `coverage-parser` to `2.1.0`.
- Adds support for LCOV https://github.com/codacy/coverage-parser/pull/37
- Updates sbt to 1.3.2
- I'm delaying the update of circle build to orbs to another task.
> Bump codacy-parser

- README.md
this fix the Gradle task instructions pointing to a stable release.
> fix: Update instructions on the gradle task

- README.md
- src/main/scala/com/codacy/rules/ReportRules.scala
- src/test/scala/com/codacy/rules/ReportRulesSpec.scala
Discover PHP Unit xml if report file not given.
Given thtat PHP Unit xmls are named index.xml, which is a common name, changed tool to succeed if one of the reports is correctly sent to the coverage service
> feature: Add PHPUnit xml format as discoverable format

- README.md
- get.sh
You should be able to run the script with installing any additional packages (see #160).
Unless we are supporting other OS, this should be enough for downloading the reporter.
> feature: Remove jq dependency

- .circleci/config.yml
- build.sbt
It doesn't make sense to publish the reporter as a library, since it is supposed to be used as a binary.
> feature: Stop publishing to sonatype

- get.sh
- The sed command contained some parts that work only with GNU sed
- This change make get.sh work again on Mac OS X
> fix: Fix get.sh set command to not use GNU sed syntax

- README.md
Added the insight from this [Slack thread](https://codacy.slack.com/archives/CL70DTJF8/p1586340959047600?thread_ts=1585817768.018700&cid=CL70DTJF8) to the Troubleshooting section.
> Add workaround for dotCover coverage reports that are too big

- README.md
PHPUnit xml format changed after version 4. And this tool does not support newer versions.
To use this tool with newer versions, users should use the flag `--coverage-clover` and send the report using the clover format.
> doc: Add version restriction to PHPUnit xml

- src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala
- src/main/scala/com/codacy/rules/commituuid/providers/GitHubActionProvider.scala
Add ability to get commit id from GitHub actions
Based on [this](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables).
> feature: Add support for GitHub Actions provider

- orbs/examples/codacy-coverage-report.yml
Avoid confusion by using real reports names
> docs: Use real report names

- src/main/scala/com/codacy/rules/ReportRules.scala
The file is now generated in a temporary folder with a unique name, instead of the same folder where the report is.
This file is used for troubleshooting purposes.
Fix #217
> fix: Change generated JSON file directory to tmp folder :breaking:

- .circleci/config.yml
Without this change, PRs from forks will fail for lack of values
> fix: Remove environment variables from tests

- src/main/scala/com/codacy/rules/ReportRules.scala
Send final report when guessing multiple files and the --partial
flag is not specified.
In this situation the previous behaviour was to send some partial
reports but without a final at the end. This way users need to
send a manual final right after.
With this change the final is sent automatically.
> fix: Send final report in automatic mode :breaking:

- docs/installation.md
Some customers feel more comfortable manually downloading the `codacy-coverage-reporter` binary files.
This was already described in the documentation, but it can be made more apparent why a customer would want to do this and how the scripts work so customers can adapt them if they wish.
More information on [this Slack thread](https://codacy.slack.com/archives/CL70DTJF8/p1593504069046700).
> Add detail on downloading binaries manually

- src/main/scala/com/codacy/rules/ReportRules.scala
As a result of https://github.com/codacy/codacy-coverage-reporter/pull/235, the page containing information on sending partial reports changed to a new location.
> fix: Update link to docs on sending partial reports

- orbs/commands/send_report.yml
I think the position of `$skip_option` from commit 7542ac is incorrect. This orb is not runnable currently on CircleCI.
Error message from CircleCI:
```
--> Download the codacy reporter codacy-coverage-reporter-linux... (latest)
######################################################################## 100.0%
######################################################################## 100.0%
2020-08-18 20:18:48.834Z  info [CodacyCoverageReporter] Skip reporting coverage  - (CodacyCoverageReporter.scala:16)
--> Succeeded!
______          __
/ ____/___  ____/ /___ ________  __
/ /   / __ \/ __  / __ `/ ___/ / / /
/ /___/ /_/ / /_/ / /_/ / /__/ /_/ /
\____/\____/\__,_/\__,_/\___/\__, /
/____/
Codacy Coverage Reporter
--> Using codacy reporter codacy-coverage-reporter-linux from cache
Unrecognized …
```
> Fix skip_option

- docs/generating-coverage-reports.md
The command provided was incomplete because it missed the `report` instruction. It is better to direct users to the main instructions on how to run codacy-coverage-reporter instead.
> doc: Direct users to instructions on how to upload coverage results

- build.sbt
- src/it/scala/com/codacy/CodacyCoverageReporterSpec.scala
- src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
- src/main/scala/com/codacy/model/configuration/Configuration.scala
- src/main/scala/com/codacy/rules/ConfigurationRules.scala
- src/main/scala/com/codacy/rules/ReportRules.scala
- src/test/scala/com/codacy/rules/ConfigurationRulesSpec.scala
- src/test/scala/com/codacy/rules/ReportRulesSpec.scala
This is the final step to give the users the possibility of choosing the Coverage Parser they want to use.
We are as well adding a log to make it easier to debug parser's issues in the future.
I will update the documentation as soon as #244 is merged.
@pauloribeiro-codacy I encourage you to go ahead, merge and eventually re-iterate!
> feature: Use a specific parser for coverage and log the used one

- docs/adding-coverage-to-your-repository.md
- docs/alternative-ways-of-running-coverage-reporter.md
- docs/troubleshooting-common-issues.md
- src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
- src/main/scala/com/codacy/rules/ConfigurationRules.scala
- src/main/scala/com/codacy/rules/ReportRules.scala
- src/test/scala/com/codacy/rules/ConfigurationRulesSpec.scala
Using the account API Token only works for repositories belonging to legacy organizations and not for synced organizations.
We may add new instructions in the future if we figure out a different solution to submit coverage for multiple repositories without having to use individual project API Tokens for each repository.
See https://codacy.atlassian.net/browse/CY-2862 for more details.
> doc: Remove instructions on how to authenticate using account API Token

- docs/adding-coverage-to-your-repository.md
- docs/alternative-ways-of-running-coverage-reporter.md
This pull request is for working on subsequent improvements to the codacy-coverage-reporter documentation identified in the pull request #244:
- Update section on Travis CI (feedback from @mrfyda "Looks like this section could be updated"). https://github.com/codacy/codacy-coverage-reporter/pull/244#discussion_r482853597
- Add list of repositories with examples of how to generate coverage (feedback from @mrfyda "Ideally, for each language we would have an example of what it takes to set up coverage and report it to Codacy. See here an example: https://github.com/codecov/example-scala"). https://github.com/codacy/codacy-coverage-reporter/pull/244#discussion_r481299879
- Figure out a better solution to list the aliases of the currently supported languages. …
> doc: Make improvements to the codacy-coverage-reporter documentation

- docs/alternative-ways-of-running-coverage-reporter.md
Apparently, the user must have changed his GitHub username and the previous link no longer works.
I'm fixing this because I enabled an automatic link checker on codacy/docs to find broken links on the documentation: https://github.com/codacy/docs/issues/219
> fix: Update link to GitHub user profile

- get.sh
`command` built-in is prefered to `which` command for 2 reasons:
- `which` is not implemented by POSIX and `command` is POSIX-compliant;
- It's always preferable to use a bash built-in command if it does what
you want. Bash does subprocess forking to execute commands inside a
subshell to maintain the current shell environment and that's expensive.
In this case, performance is obviously not an issue, but I think portability
is very important for this situation.
Reference: http://www.skybert.net/bash/making-your-bash-programs-run-faster/
Reference: https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then
Signed-off-by: Luís Ferreira <contact@lsferreira.net>
> fix: Rely on bash built-in instead of coreutils implementation

- src/main/scala/com/codacy/rules/ReportRules.scala
Currently the behaviour is to fail guessing language if the first file has an extension we don't support.
This change makes the guesser continue to iterate on file until it finds a file for a language Codacy supports and uses that language file.
This is a temporary workaround until a more complete ( something like https://github.com/codacy/codacy-coverage-reporter/pull/269 ) lands.
> fix: Improve language guessing by stopping at first supported language CY-3145

- docs/adding-coverage-to-your-repository.md
This is a minor edit to clarify that the API tokens grant owner permissions to the Codacy repositories.
Before, one could think that they granted permissions to the repositories on the Git provider, which isn't true.
> doc: Clarify warning on keeping API tokens safe

- src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala
- src/main/scala/com/codacy/rules/commituuid/providers/AzurePipelinesProvider.scala
Tested here: https://dev.azure.com/lolgab/azure-test/_build/results?buildId=14&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86
With this pipelines
```yaml
trigger:
- main
pool:
vmImage: 'ubuntu-latest'
steps:
- script: echo Hello, world!
displayName: 'Run a one-line script'
- script: |
java -jar codacy-coverage-reporter-assembly-0.0.1-SNAPSHOT.jar report --project-token 123
echo $(Build.SourceVersion)
echo "$BUILD_SOURCEVERSION"
echo $TF_BUILD
displayName: 'Run a multi-line script'
```
> feature: Support Azure Pipelines CY-3311

- README.md
- docs/adding-coverage-to-your-repository.md
- docs/alternative-ways-of-running-coverage-reporter.md
Currently, from the README it's not very clear that there are multiple ways to run the Codacy Coverage Reporter. In particular, users who cannot run the Coverage Reporter on macOS Big Sur have trouble figuring out that they can use the Java binary as a workaround.
See https://github.com/codacy/codacy-coverage-reporter/issues/276 and [CY-3404](https://codacy.atlassian.net/browse/CY-3404) for more details.
> doc: Refactor how to run Codacy Coverage Reporter

- docs/adding-coverage-to-your-repository.md
The previous pull request https://github.com/codacy/codacy-coverage-reporter/pull/284 failed to update this page.
> fix: Update missing dotCover detailedXML report format

- build.sbt
Includes the changes from https://github.com/codacy/codacy-api-scala/pull/42.
> bump: Bump codacy-api-scala to 5.0.1

- .circleci/config.yml
- docs/alternative-ways-of-running-coverage-reporter.md
- get.sh
This PR started considering that in Travis CI the `after_success` phase runs after the cache has been saved.
So to cache the binary we need a separate phase that just downloads the binary without sending any coverage.
This also caches the binary based on the version so we're sure the binary gets updated when a new version is out.
> Download command in script

- orbs/commands/send_report.yml
Now that cache is versioned the latest version is chosen only when `CODACY_REPORTER_VERSION` is empty \([here](https://github.com/codacy/codacy-coverage-reporter/blob/master/get.sh#L106)\).
The integration test that failed is flaky.
> fix: Fix CircleCI orb when version is not defined

- .circleci/config.yml
This is a 2 step process:
1. start publishing to bintray (this PR)
2. change get.sh script to retrieve from public s3 (coming soon...)
This will guarantee that the script usages will have no downtime
> feature: publish to s3 instead of bintray

- docs/adding-coverage-to-your-repository.md
Before, the order of the flags in the instructions did not match the order in the example and there was a typo in the flag `--coverage-reports`.
> doc: Improve instructions on how to upload partial reports

- docs/adding-coverage-to-your-repository.md
The Codacy Coverage Reporter must run (or is recommended that it runs?) on the root of a locally checked out branch of the Git repository.
Also, it's more explicit to recommend specifying the path to the coverage report manually since the Coverage Reporter may not find all coverage report files (for example, if they're in a subdirectory).
Fixes https://github.com/codacy/docs/issues/479 (user submitted feedback).
> doc: Clarify how to run codacy-coverage-reporter

- docs/adding-coverage-to-your-repository.md
Simplified the explanation of how the Coverage Reporter detects the current commit.
Also added the flag `-r` to make running the command more explicit.
> doc: Simplify section "Commit SHA hash detection"

- docs/troubleshooting-common-issues.md
After the investigation in [CY-3801](https://codacy.atlassian.net/browse/CY-3801) we came to the conclusion that the recommended workaround for [this issue](https://community.codacy.com/t/issue-getting-malformedinputexception-input-length-1-when-uploading-lcov-info-from-github-actions/181) would be to make sure that the coverage report is encoded using UTF-8.
> feature: Add workaround for MalformedInputException DOCS-217

- docs/index.md
A previous change had introduced spurious "escape characters" in the filenames of some test coverage reports:
https://github.com/codacy/codacy-coverage-reporter/pull/244/files#diff-8822c8c2af34cf045623870b3ecb526998c4a29a0c859b3cfa1921fb0c11cac6R12-R13
> doc: Remove spurious "\" in test coverage report filenames

- docs/index.md
It's possible to upload multiple test coverage reports using a single command. This also makes it easier to find and specify multiple report files dynamically.
:construction: **Should we keep the information in red or is it just adding unnecessary complexity in the documentation?** Plase see the comments below.
See [this Slack thread](https://codacy.slack.com/archives/C8X9SS1H7/p1615805679001700) for more details.
> doc: Add simplified way of uploading multiple coverage reports

- docs/index.md
The API tokens page moved to a new section dedicated to the Codacy API (see [DOCS-224](https://codacy.atlassian.net/browse/DOCS-224)).
> doc: Update link to API tokens and warning on keeping tokens secure

- .circleci/config.yml
Includes the fix from https://github.com/codacy/codacy-orbs/pull/146 and applies the same fix to the job `it_coverage_script_macosx`.
> bump: Update codacy/base orb to latest version

- docs/alternative-ways-of-running-coverage-reporter.md
- docs/index.md
- docs/troubleshooting-common-issues.md
Add explicit meta descriptions to each documentation page, necessary to complete https://github.com/codacy/docs/pull/585.
> doc: Add meta descriptions to documentation pages DOCS-227

- docs/index.md
Small improvement to make the links to instructions on how to obtain API tokens more actionable.
> doc: Improve links to instructions on obtaining API tokens

- docs/alternative-ways-of-running-coverage-reporter.md
- docs/index.md
Review and curate the meta descriptions of the [top landing pages for Google searches](https://docs.google.com/spreadsheets/d/191E8aGjiJwpSp8sroPZQUeZMmSiJ7t2HHLFGnJvkhEE/edit#gid=566714567).
> doc: Improve meta descriptions of top searched pages DOCS-227

- README.md
A customer was having issues with using the api-token when reporting coverage. Turns out he was using the '-t' flag and it looks like we had a typo in the README.
> Fixing flag description for Api-Token

- docs/index.md
Fixes https://github.com/codacy/docs/issues/685.
> doc: Fix broken link to PHPUnit documentation

- docs/index.md
- docs/troubleshooting-common-issues.md
This was [suggested](https://github.com/codacy/codacy-coverage-reporter/pull/320#issuecomment-847631330) by @mrfyda. :raised_hands: 
Moves the sections [Submitting coverage for unsupported languages](https://docs.codacy.com/coverage-reporter/troubleshooting-common-issues/#submitting-coverage-for-unsupported-languages) and [Submitting coverage from unsupported report formats](https://docs.codacy.com/coverage-reporter/troubleshooting-common-issues/#unsupported-report-formats) to the main documentation page on how to set up coverage.
By creating subsections of the main steps for setting up coverage (generating the coverage reports and then uploading the report to Codacy) I'm trying to keep the complexity of the main page controlled while avoiding the need for users to find and jump to …
> doc: Move most important troubleshoot sections to main page

- docs/index.md
This was [initially suggested](https://github.com/codacy/codacy-coverage-reporter/pull/321#discussion_r638642732) by @mrfyda, and I also have many doubts that this information can be useful. With all the different conversion tools that are available, I just can't imagine users building their own tool to translate coverage data into our JSON format so they can call the API endpoints.
This said I would even prefer to remove the reference to the API endpoints completely and keep this simple. What do you think?
> doc: Remove explanation on how to upload coverage using the Codacy API

- docs/index.md
Adds extra information about the values that users must set as environment variables. In particular, the variable `CODACY_USERNAME` must contain either the name of the organization or the username on the Git provider when using a personal organization.
Preview of the updated section:
https://github.com/codacy/codacy-coverage-reporter/blob/fix/env-username-organization-DOCS-277/docs/index.md#2-uploading-coverage-data-to-codacy--iduploading-coverage
Fixes https://github.com/codacy/docs/issues/757.
> fix: Add environment variable details when using account API token DOCS-277

- docs/alternative-ways-of-running-coverage-reporter.md
As mention on #329 the Java binary is intended for Java 8
> doc: Clarify that the Java binary only works for Java 8 CY-4663

- README.md
- build.sbt
- src/it/scala/com/codacy/CodacyCoverageReporterSpec.scala
- src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
- src/main/scala/com/codacy/model/configuration/Configuration.scala
- src/main/scala/com/codacy/rules/ConfigurationRules.scala
- src/main/scala/com/codacy/rules/ReportRules.scala
- src/test/scala/com/codacy/rules/ReportRulesSpec.scala
Also fixes the tests that were failing due to timeout.
Depends on: https://github.com/codacy/codacy-api-scala/pull/45
> feature: Add --http-timeout option for custom timeouts when interacting with Codacy API CY-4834

- .circleci/config.yml
Did some tests with some test/ branch and pre-releases and it they have been successfully published. This PR will start to store the SHA together with the release on GH, so on a follow up PR we can update the get.sh script to check the checksums against the binaries that come from artifacts.codacy.com.
> Add checksums as part of the GitHub release artifacts CY-4457

- get.sh
We already had a CODACY_REPORTER_VERSION and now are adding a CODACY_REPORTER_SKIP_CHECKSUM, any place where you guys think we could mention it? @prcr 
This will check for the checksum of the binaries >= 12.4.0 and only if CODACY_REPORTER_SKIP_CHECKSUM is not set to `true`
> Check checksum when downloading binaries CY-4457

- README.md
- get.sh
CODACY_REPORTER_SKIP_CHECKSUM=true will skip the check
This is the de facto version that starts to check it,
it was 12.4.0 before for bootstraping purposes
> feature: Only do checksum for versions >= 13.0.0

- get.sh
On some envs we are seeing `line 102: sha512sum: command not found`, but `shasum` is installed. This change adds checks for both the `sha512sum` and `shasum` binaries, and exits out if neither is found.
> Add checks and alternative for missing sha512sum command

- .circleci/config.yml
- docs/alternative-ways-of-running-coverage-reporter.md
- get.sh
It seems that some versions of sha512sum only support the -c mode
For the other checked versions, it does support both modes.
Example:
```
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.
Usage: sha512sum [-c[sw]] [FILE]...
Print or check SHA512 checksums
-c	Check sums against list in FILEs
-s	Don't output anything, status code shows success
-w	Warn about improperly formatted checksum lines
```
While others have
```
-c, --check          read SHA512 sums from the FILEs and check them
```
> fix: Use -c flag over --check

- README.md
For some reason, there were two Codacy badges on the README but none was working:
> fix: Update Codacy badge on README

- docs/index.md
- docs/troubleshooting-common-issues.md
I didn't notice this while working on https://github.com/codacy/codacy-coverage-reporter/pull/342.
> doc: Make placeholder for coverage report consistent

- get.sh
Adds the logs suggested at https://github.com/codacy/codacy-coverage-reporter/pull/345 thanks @0xced.
This will print the expected and actual checksum for both failure and success.
> feature: Add logs for the SHA512 used during checksum verification

- get.sh
As mention by @tobiasweibel at https://github.com/codacy/codacy-coverage-reporter/pull/335#discussion_r691186185, the pushd and popd are an enhancement of the POSIX standard in the bash shell.
There can be some cases where the shell don't have access to those commands.
> feature: Stop using pushd and popd for better compatibility

- README.md
- docs/troubleshooting-common-issues.md
- get.sh
Following the [feedback](https://codacy.atlassian.net/browse/CY-4874?focusedCommentId=47679) from @dan-codacy and other reports from users who have had issues with the checksum calculation, we should make the workaround for disabling the checksum calculation more visible, directly in the existing [troubleshooting page](https://docs.codacy.com/coverage-reporter/troubleshooting-common-issues/).
> doc: Include workaround for checksum issues in troubleshooting CY-4874

- docs/index.md
Preview of the new section on the page [Adding coverage to your repository](https://docs.codacy.com/coverage-reporter/):
Fixes https://github.com/codacy/docs/issues/807.
> doc: How to upload the same coverage report for multiple languages DOCS-289

- docs/troubleshooting-common-issues.md
Adds a small troubleshooting section for the scenario where the Codacy Coverage Reporter successfully uploads the coverage data but it doesn't become visible on the Codacy UI. The cause can either be a mismatch in the file paths included in the coverage reports or a wrong commit UUID being reported.
Fixes https://github.com/codacy/codacy-coverage-reporter/issues/234.
> feature: Troubleshooting for coverage missing in Codacy UI DOCS-222

- docs/index.md
Clarifies that users must wait until the second commit to start seeing the coverage information on the Codacy UI.
Preview of the page:
https://github.com/codacy/codacy-coverage-reporter/blob/b1279df30c9416d920fab7552f71bf000421db57/docs/index.md#2-uploading-coverage-data-to-codacy--iduploading-coverage
> doc: Codacy only displays coverage after the second commit DOCS-307

- README.md
- src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
The flag `--language` forces associating a language to the coverage report being uploaded, not to the repository, as seen here:
https://github.com/codacy/codacy-coverage-reporter/blob/doc/update-language-flag/src/main/scala/com/codacy/rules/ReportRules.scala#L175-L197
This pull request applies a change similar to [the one from codacy-coverage-reporter-action](https://github.com/codacy/codacy-coverage-reporter-action/pull/57#pullrequestreview-855781715) to this repository.
> doc: Update description for the flag --language

- docs/alternative-ways-of-running-coverage-reporter.md
Based on feedback from @mrfyda (see [Slack thread](https://codacy.slack.com/archives/C02V7GU5Y2V/p1643275631028700)), this is a very low-effort way of improving the visibility of our GitHub Action and CircleCI orb.
> doc: Reorder alternative ways of running the Coverage Reporter

- docs/index.md
The previous syntax would only find reports called `jacoco*.xml` inside the **first level of subdirectories**.
The updated command ensures that any file `jacoco*.xml` will be found not only across all levels of subdirectories but on the root of the repository as well.
> doc: Fix find command syntax

- docs/index.md
[Coverlet](https://github.com/coverlet-coverage/coverlet) is a popular code coverage framework for C#/.NET that can also output coverage report files in formats supported by the Codacy Coverage Reporter.
Fixes https://github.com/codacy/docs/issues/1020.
> doc: Add Coverlet as supported coverage tool for C# DOCS-350

- README.md
- src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
- src/main/scala/com/codacy/rules/ConfigurationRules.scala
- src/test/scala/com/codacy/rules/ReportRulesSpec.scala
The intent is for the http-timeout only increase the readTimeout which was the initial intention.
For the connection timeout, changing it to 1000, as it is the default from the lib, so it goes back to the behaviour it had before https://github.com/codacy/codacy-coverage-reporter/pull/380 regarding connection timeout
> fix: Use the http-timeout for the read-timeout only CY-6106

- docs/index.md
This change tries to make it more explicit that users reporting multiple coverage reports must use the `final` command after uploading all reports.
> doc: Use ordered list to clarify how to use --partial and final

- docs/troubleshooting-common-issues.md
Improves the troubleshooting for the error `java.nio.charset.MalformedInputException` when uploading a coverage report.
According to this [Stack Overflow thread](https://stackoverflow.com/questions/26268132/all-inclusive-charset-to-avoid-java-nio-charset-malformedinputexception-input) and by looking at our coverage report parser implementation we're using the default character encoding UTF-8 while reading the coverage reports. This had also [been validated](https://codacy.atlassian.net/browse/CY-3801?focusedCommentId=45707) by @lolgab. So, any character outside of this charset will throw the exception.
As a suggestion, would it be possible to make the Codacy Coverage Reporter more robust to this type of errors - either by reading/parsing the report correctly or by outputting a helpful …
> doc: Improve recommendation for fixing MalformedInputException DOCS-349

- docs/alternative-ways-of-running-coverage-reporter.md
Small edit to clarify that users must substitute `<version>` when running the `docker run` command.
> doc: Clarify specifying the Docker image version

- docs/alternative-ways-of-running-coverage-reporter.md
Substitutes the broken Gradle task examples with a simple task that always runs the latest version of the Codacy Coverage Reporter using the recommended command `bash <(curl -Ls https://coverage.codacy.com/get.sh)`.
Fixes https://github.com/codacy/codacy-coverage-reporter/issues/389.
https://github.com/codacy/codacy-coverage-reporter/blob/doc/update-gradle-example-DOCS-389/docs/alternative-ways-of-running-coverage-reporter.md#gradle-task
> doc: Update Gradle task example DOCS-389

- docs/troubleshooting-common-issues.md
Recommend using the flag `--http-timeout` to increase the default timeout of 10 seconds while connecting to the Codacy API and overcome the `Error doing a post to ... connect timed out` error.
Fixes https://github.com/codacy/codacy-coverage-reporter/issues/383.
> doc: Add troubleshooting for "connect timed out" error DOCS-381 CY-6072

- .circleci/canWorkflowStart.py
- .circleci/config.yml
Quick effort to prevent problems publishing the reporter due to concurrently running workflows. This does a similar behaviour from the implementation in the QA suites:
- introduce a new step in the beginning of the workflow to actively wait for a slot to run (through python script)
- poll circleci API for existing pipelines for the current branch
- if any exist check if their workflows are in running state
- if any, wait and try again in some minutes
This can be followed up by abstracting this to `codacy-orbs`
> feature: prevent concurrent ci workflows runs on the same branch

- docs/index.md
After [receiving feedback from a user](https://app.intercom.com/a/apps/a53cb793563c5f92959598bf8b22fe8f01ec3199/inbox/inbox/conversation/1644200179523) we realized that it's more explicit to include the optional path in the `find` command.
> doc: Add explicit starting path to find command

- docs/index.md
Adds a checklist of the information necessary to troubleshoot the coverage setup and that users should include when contacting Support to make the process more efficient.
https://feature-update-codacy-coverage-repo--docs-codacy.netlify.app/coverage-reporter/#validating-coverage
> doc: Add guidelines for contacting Support DOCS-394

- README.md
- src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
- src/main/scala/com/codacy/model/configuration/Configuration.scala
- src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala
@mrfyda and I reached the conclusion that the Codacy Coverage Reporter is using the internal Codacy lingo "commit UUID" when referring to what's known by most developers as the "commit SHA-1 hash".
This is a proposal to change the way we refer to the SHA-1 hash in the CLI output of the Codacy Coverage Reporter.
> docs: Change commit UUID to commit SHA-1 hash

- docs/alternative-ways-of-running-coverage-reporter.md
- docs/index.md
- docs/uploading-coverage-in-advanced-scenarios.md
- mkdocs.yml
The [main page with instructions for setting up coverage](https://docs.codacy.com/coverage-reporter/) is getting too big, making it hard to follow through the complete sequence of instructions.
This pull request:
- Moves the instructions for more advanced scenarios to a dedicated page
- Tweaks a few references and admonitions so that they appear in the sequence that makes the most sense while users are configuring their setup
These improvements will give way to more detailed troubleshooting instructions for the most common coverage setup failure scenarios (see [CY-6263](https://codacy.atlassian.net/browse/CY-6263)).
> doc: Refactor coverage documentation

- docs/index.md
- docs/troubleshooting-common-issues.md
Refactors the coverage documentation to group together all setup validation steps, ordered to make it easier for users to catch any setup issues as early as possible during the validation.
Together with https://github.com/codacy/codacy-coverage-reporter/pull/406, these improvements will give way to more detailed troubleshooting instructions for the most common coverage setup failure scenarios (see [CY-6263](https://codacy.atlassian.net/browse/CY-6263)).
> doc: Refactor coverage setup validation CY-6365

- docs/index.md
As reported by @mrfyda, Codacy reports the coverage status **Pending** if the file paths in the coverage report don't match the relative paths starting at the root of the repository, as displayed on the **Files** page.
Because of this, the troubleshooting for this scenario can be included in the table instead of at a later step.
> doc: Move mismatched file paths troubleshooting to Pending state CY-6365

- docs/index.md
I forgot to update the rowspan value while adding a new table row in https://github.com/codacy/codacy-coverage-reporter/pull/414.
> doc: Fix rowspan on coverage troubleshooting table

- src/main/scala/com/codacy/rules/ReportRules.scala
- src/test/scala/com/codacy/rules/ReportRulesSpec.scala
For each coverage report file, the coverage reporter will:
- look through the files that are referenced in the report and extract its language by looking at file extensions
- if there are many languages, it will pick the first one and report all coverage as that language
This is problematic since it is not visible to the users (they just call our script) and it is possible that a report contains results for multiple languages.  
If you set the `-l` parameter it will override this behavior, but you must send the same report multiple times, one per language.
When we make the decision to pick a specific language, we now output:
- that it is happening, 
- in what file, 
- what other languages were detected, and 
- a link to the relevant documentation.
> feature: warn user when multiple languages are detected IO-52

- docs/index.md
Adds IDs to the coverage status troubleshooting table so that we can create direct anchor links for each error status.
> doc: Add IDs for each coverage error status table row CY-6365

- .github/CODEOWNERS
Adds the GitHub group @codacy/techwriters as CODEOWNERS of the `/docs/` directory.
> doc: Add @codacy/techwriters as /docs/ CODEOWNERS

- docs/index.md
If the common ancestor commit between a pull request and the target branch is missing coverage data, developers can rebase the branch to ensure that Codacy can calculate both coverage metrics.
> doc: Suggest rebasing branch to fix missing coverage variation

- docs/index.md
Refactors the coverage error status troubleshooting table into separate sections.
This has two advantages:
- Makes it much more straightforward to have permalinks for each error status
- Makes sure that when users navigate directly to each error status they see the full troubleshooting table for that status, namely the heads that are required to correctly interpret the information
https://feat-update-codacy-coverage-reporte--docs-codacy.netlify.app/coverage-reporter/#status-commit-not-found
> doc: Split troubleshooting table into sections IO-233

- get.sh
Bumping coverage-reporter version to the latest version: `13.13.0`.
> bump: Self hosted version to 13.13.0 for SH release 11.0.0

- coverage-parser/src/main/scala/com/codacy/parsers/implementation/CoberturaParser.scala
- coverage-parser/src/main/scala/com/codacy/parsers/util/MathUtils.scala
- coverage-parser/src/test/resources/test_cobertura.xml
- coverage-parser/src/test/scala/com/codacy/parsers/CoberturaParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/CoverageParserFactoryTest.scala
> fix: Use `BigInt` instead of `Long` in `toIntOrMaxValue` TS-549

- build.sbt
- src/main/scala/com/codacy/rules/commituuid/providers/GitHubActionProvider.scala
> clean: Avoid depending on two json libraries

- .circleci/config.yml
- api-scala/src/main/scala/com/codacy/api/CoverageReport.scala
- api-scala/src/main/scala/com/codacy/api/helpers/vcs/GitClient.scala
- api-scala/src/test/scala/com/codacy/api/GitClientTest.scala
- build.sbt
- coverage-parser/src/main/scala/com/codacy/parsers/implementation/CloverParser.scala
- coverage-parser/src/test/scala/com/codacy/parsers/CloverParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/CoberturaParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/CoverageParserFactoryTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/CoverageParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/DotCoverParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/GoParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/JacocoParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/LCOVParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/OpenCoverParserTest.scala
- coverage-parser/src/test/scala/com/codacy/parsers/PhpUnitXmlParserTest.scala
- src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
- src/main/scala/com/codacy/rules/ConfigurationRules.scala
- src/main/scala/com/codacy/rules/ReportRules.scala
- src/test/scala/com/codacy/model/configuration/CommitUUIDSpec.scala
- src/test/scala/com/codacy/rules/ConfigurationRulesSpec.scala
- src/test/scala/com/codacy/rules/ReportRulesSpec.scala
- src/test/scala/com/codacy/rules/commituuid/CommitUUIDProviderSpec.scala
- src/test/scala/com/codacy/rules/commituuid/providers/GitHubActionProviderSpec.scala
- src/test/scala/com/codacy/transformation/FileNameMatcherSpec.scala
- src/test/scala/com/codacy/transformation/GitFileNameUpdaterAndFilterSpec.scala
- src/test/scala/com/codacy/transformation/PathPrefixerSpec.scala
Scala 3 case-app doesn't depend on shapeless anymore, which should reduce the binary size
This also updates dependencies to their Scala 3 compatible counterpart
- `case-app` is updated to `2.1.0-M28`
- `airframe-log` is updated to `24.6.0`
- `mockito` is replaced with `scalamock` which supports scala 3
- `scalatest` is updated to `3.2.18`
- `play-json` is updated to `2.10.5`
- `codacy-plugins-api` is updated to `8.1.4`
- `scala-xml` is updated to `2.3.0`
> breaking: Update to Scala `3.3.3`

- api-scala/src/main/scala/com/codacy/api/helpers/vcs/GitClient.scala
last file was not being properly retrieved ALA-1387
> fix: fixes extraction of repository files ALA-1387

- src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala
- src/main/scala/com/codacy/rules/commituuid/providers/BitbucketCloudProvider.scala
Just copying the work done by [@dangllucas](https://github.com/dangllucas) on this [PR](https://github.com/codacy/codacy-coverage-reporter/pull/524) for pipeline reasons
> feature: Support Bitbucket Cloud Pipelines
