README.md

Replaced Python language argument by Java

Fix typo on command

---

.travis.yml
README.md
circle.yml
project/plugins.sbt
src/main/scala/com/codacy/CodacyCoverageReporter.scala
src/test/scala/com/codacy/CodacyCoverageReporterTest.scala
src/test/scala/com/codacy/transformation/PathPrefixerTest.scala

Add badges to docs.
Add coverage to codacy.
Add some tests.
Changed some strings, and some extract method.

Add coverage to codacy

---

project/plugins.sbt

This will allow users to use builds from source

Add assembly plugin

---

README.md

Add issue troubleshooting https://github.com/codacy/codacy-coverage-reporter/issues/11

Update README.md with troubleshooting

---

README.md

troubleshooting instructions were based on interactions with Codacy support team

Updated Troubleshooting instructions

---

README.md

Add maven plugin information to README

---

build.sbt
project/Dependencies.scala
src/main/resources/logback-test.xml
src/main/scala/com/codacy/CodacyCoverageReporter.scala
src/test/scala/com/codacy/CodacyCoverageReporterTest.scala
src/test/scala/com/codacy/transformation/PathPrefixerTest.scala

Allow unknown languages

---

src/main/scala/com/codacy/CodacyCoverageReporter.scala

Fix options output

---

project/Dependencies.scala

Depends on https://github.com/codacy/coverage-parser/pull/14

Updated dependency of coverage parser

---

README.md

We no longer use jpm to install the reporter

Remove jpm from Readme

---

README.md
build.sbt
project/Dependencies.scala

Fixes #76 and #83 
Based on https://github.com/codacy/sbt-codacy-coverage/pull/54
Thanks to @Raffaello in https://github.com/codacy/sbt-codacy-coverage/issues/53

Add javax activation

---

README.md

fixes jq parsing error

---

README.md
src/main/scala/com/codacy/rules/ConfigurationRules.scala

https://scrutinizer-ci.com/docs/build/environment-variables

Add support to scrutinizer-ci

---

README.md
scripts/publish-native.sh

Here we propose to bump GraalVM to 19.3.0 to properly include `libsunec.so`.
There is known bug in GraalVM and DNS resolution( https://github.com/oracle/graal/issues/624 ), so here I propose a workaround.
Please @ljmf00 doublecheck and take over this.

Fix SSL Hanshake and DNS issues

---

README.md
build.sbt
src/main/scala/com/codacy/rules/ReportRules.scala

coverage-parser new version includes parsers for new coverage reports formats

bump: Raise coverage-parser version

---

README.md

I was checking the README.md for this project and would like to propose a few small improvements.

Small suggestions to improve README.md

---

get.sh

https://github.com/codacy/codacy-coverage-reporter/issues/160

feature: get.sh script get native version when on linux distro

---

README.md
docs/authentication.md
docs/commit_detection.md
docs/installation.md

Simplify README by moving less relevant information to other files.

docs: clean up README

---

src/main/scala/com/codacy/rules/ReportRules.scala

The token can now be either a project or account token

docs: Update NotFound error message

---

.github/codacy-coverage-reporter.yml
README.md
docs/installation.md

I was testing the installer script and ended up doing this action.
If we decide to merge:
(Depends on #168)

feature: Add GitHub Action

---

.circleci/config.yml
.github/CODEOWNERS
get.sh
integration-tests/mock-server-config.json
integration-tests/mock-server-error-config.json
integration-tests/test_dotcover.xml

Add integration test for Alpine based systems
Add integration test for Ubuntu based systems

test: Add integration tests for get.sh script

---

.circleci/config.yml

Three commits here for the 3 fixes :-)

Fixes to the IT tests

---

.circleci/config.yml
get.sh
project/build.properties

feature: Add native binaries for Darwin

---

docs/commit_detection.md
src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala
src/main/scala/com/codacy/rules/commituuid/providers/HerokuCIProvider.scala

Adding support for Heroku CI
https://devcenter.heroku.com/articles/heroku-ci

feat: Add Heroku CI support

---

orbs/commands/send_report.yml
orbs/examples/codacy-coverage-report.yml

https://github.com/codacy/codacy-meta/issues/345

feature: Add project token and coverage reports to CircleCI orb :breaking:

---

src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala

fix: Coverage reporter helper usage with correct command on native image

---

orbs/commands/send_report.yml

Modifying run to have a name and improve the CircleCI step logs.

clean: Add name to the command step

---

docs/index.md

Reported by Mark:
https://codacy.slack.com/archives/C011BCR2RN3/p1595254967000700

doc: Fix typo

---

orbs/commands/send_report.yml

I manually tested it with ubuntu/alpine and curl/wget matrix ...
Not sure how we can automate tests here ...

fix: Make the orb compatible with Alpine Linux executors

---

build.sbt

bump: Update coverage parser with clover improvements

---

docs/adding-coverage-to-your-repository.md

This update is related to https://github.com/codacy/codacy-coverage-reporter/pull/274 and [CY-3311](https://codacy.atlassian.net/browse/CY-3311).

doc: Add commit UUID detection support for Azure Pipelines

---

docs/troubleshooting-common-issues.md

Fixes a broken link detected in https://github.com/codacy/docs/issues/367.

fix: Update broken link

---

get.sh
orbs/commands/send_report.yml

Revert useless tool_version check in CircleCI orb

Fix CircleCI old versions using latest as version default

---

docs/alternative-ways-of-running-coverage-reporter.md
get.sh

feature: use new source for binaries and update docs

---

docs/index.md

Fixes https://github.com/codacy/docs/issues/549.

doc: Update Mocha homepage link

---

docs/troubleshooting-common-issues.md

Also organized the several recommended converters in a list with a short description.
This addresses the feedback kindly provided by a customer: https://codacy.productboard.com/insights/all-notes/notes/14896874

doc: Add extra report converter for Elixir projects

---

docs/index.md

Small style changes to keep consistency with https://github.com/codacy/codacy-analysis-cli-action/pull/48.

doc: Simplify instructions on how to set up API tokens

---

docs/troubleshooting-common-issues.md

Initially submitted by @dan-codacy on this pull request: https://github.com/codacy/handbook/pull/121

doc: Add tool to convert Apex coverage to supported format

---

get.sh

Opened from the work done by @martinbutt at https://github.com/codacy/codacy-coverage-reporter/pull/338

Add checks and alternative for missing sha512sum command

---

docs/troubleshooting-common-issues.md

For more information see the Slack thread:
https://codacy.slack.com/archives/C8X9SS1H7/p1629216704039900

doc: Mention 10 MB limit when uploading coverage data DOCS-283

---

docs/index.md
docs/troubleshooting-common-issues.md

Fixes a couple of nags that I noticed while working on #341.

doc: Small style edits

---

docs/index.md

See https://github.com/codacy/docs/pull/984 for details.

clean: Replace "test coverage" with "code coverage"

---

.circleci/config.yml

clean: Use --password-stdin for docker login

bump: Bump codacy/base orb to 6.1.4

---

.circleci/config.yml

feature: Publish stable docker image CY-5837

---

.circleci/config.yml
docs/index.md

Updates docs markup to match CSS rule updates on https://github.com/codacy/codacy-mkdocs-material/pull/65

doc: Update id attribute position in document tree - IO-233

---

README.md
src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
src/main/scala/com/codacy/rules/ReportRules.scala
src/test/scala/com/codacy/rules/ReportRulesSpec.scala

Fixes: https://github.com/codacy/codacy-coverage-reporter/issues/443

feature: Support globs in --coverage-reports

---

coverage-parser/src/main/scala/com/codacy/parsers/implementation/CoberturaParser.scala
coverage-parser/src/test/resources/test_cobertura.xml
coverage-parser/src/test/scala/com/codacy/parsers/CoberturaParserTest.scala
coverage-parser/src/test/scala/com/codacy/parsers/CoverageParserFactoryTest.scala
graalvm/build-deps.sh

This fix is specific for Cobertura. Other formats need to be checked and we need to verify if they have the same problem.

fix: [Cobertura] Merge results on the same line instead of replacing

---

get.sh

* Fixes #327
* Fixes #471
Author: @marvinruder

Use Java version on architectures other than x86_64

---

coverage-parser/src/main/scala/com/codacy/parsers/util/MathUtils.scala

[TS-549] use BigInt instead of long in toIntOrMaxValue

---

api-scala/src/main/scala/com/codacy/api/helpers/vcs/GitClient.scala
build.sbt
coverage-parser/src/main/scala/com/codacy/parsers/implementation/CloverParser.scala
coverage-parser/src/main/scala/com/codacy/parsers/implementation/JacocoParser.scala
coverage-parser/src/test/scala/com/codacy/parsers/CoverageParserTest.scala
coverage-parser/src/test/scala/com/codacy/parsers/JacocoParserTest.scala
integration-tests/mock-server-config.json
integration-tests/test_dotcover.xml
src/main/scala/com/codacy/di/Components.scala
src/main/scala/com/codacy/rules/ReportRules.scala
src/main/scala/com/codacy/rules/file/GitFileFetcher.scala
src/main/scala/com/codacy/transformation/FileNameMatcher.scala
src/main/scala/com/codacy/transformation/GitFileNameUpdaterAndFilter.scala
src/test/scala/com/codacy/rules/ReportRulesSpec.scala
src/test/scala/com/codacy/transformation/FileNameMatcherSpec.scala
src/test/scala/com/codacy/transformation/GitFileNameUpdaterAndFilterSpec.scala

file name will be according to git file structure ALA-792

feature: only files in git will be considered in the report ALA-792

---

src/main/scala/com/codacy/rules/ReportRules.scala
src/test/resources/non-git-report.xml
src/test/scala/com/codacy/rules/ReportRulesSpec.scala

stops returning failure when at least one report is sent ALA-799

feature: stops failure when at least one report is sent ALA-799

---

src/main/scala/com/codacy/CodacyCoverageReporter.scala
src/main/scala/com/codacy/rules/ConfigurationRules.scala

fix: Skip only when none of auth mechanism are available

---

api-scala/src/main/scala/com/codacy/api/CoverageReport.scala
api-scala/src/main/scala/com/codacy/api/util/JsonOps.scala
build.sbt
coverage-parser/src/main/scala/com/codacy/parsers/implementation/CoberturaParser.scala
coverage-parser/src/main/scala/com/codacy/parsers/implementation/JacocoParser.scala
coverage-parser/src/main/scala/com/codacy/parsers/implementation/PhpUnitXmlParser.scala
project/plugins.sbt
src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala
src/main/scala/com/codacy/rules/ConfigurationRules.scala
src/main/scala/com/codacy/rules/ReportRules.scala

bump: Update `case-app` to 2.1.0-M14

---

build.sbt
src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala

This updates case-app to its current latest version.

bump: Update case-app to 2.1.0-M26

---

api-scala/src/main/scala/com/codacy/api/client/CodacyClient.scala
build.sbt

Reverts codacy/codacy-coverage-reporter#496

Revert "clean: Replace scalaj with sttp"

---

.circleci/config.yml

This reverts commit 85fe6a1ae6e4022188e2a8d05600c5ed5c1c7642.

Revert "fix: Remove coverage for now"
